### ISSUE TITLE
Big Sur for X230

### ISSUE THREAD

**Issue by banhbaoxamlan** [banhbaoxamlan/X230-Hackintosh#1]
Relax ...

**Comment by jamesfawcett** [comment]
I just landed here whilst trying to fix sleep issues on my X201 running Catalina! Watching your progress, this looks very interesting!

**Comment by banhbaoxamlan** [comment]
OpenCore 0.6.1
[EFI.zip](https://github.com/banhbaoxamlan/X230-Hackintosh/files/5134727/EFI.zip)

**Comment by matthew-dong001** [comment]
有上big sur吗
