### ISSUE TITLE
ssdtprgen

### ISSUE THREAD

**Issue by tpadev** [banhbaoxamlan/X230-Hackintosh#10]
From your config.plist

I see that drop CpuPm and drop Cpu0Ist set to True
 
Isn’t that suppose to be set False, after create the SSDT-PM.aml? I am following from dortania guide.

Which one is correct, and how do we know we have the correct power management for the CPU ?

**Comment by banhbaoxamlan** [comment]
> From your config.plist
> 
> I see that drop CpuPm and drop Cpu0Ist set to True
> 
> Isn’t that suppose to be set False, after create the SSDT-PM.aml? I am following from dortania guide.
> 
> Which one is correct, and how do we know we have the correct power management for the CPU ?

All correct, if u use with Windows, set it to false
open ioregistryexplorer, if u see CPU0 have X86PlatformPlugin, u have correct pm
