### ISSUE TITLE
Thank you for sharing this project!

### ISSUE THREAD

**Issue by lese9855** [banhbaoxamlan/X230-Hackintosh#11]
I'm sorry that this piece of writing is not an issue report.
I just want to say thank you for sharing this project.

I'm the another guy using X230 with macOS, and also developing it.
Recently I've tried to install macOS 11.0 Big Sur on X230 with my own EFI, and it almost worked perfectly.
Just one point made me a trouble - when I connected an eGPU on it, the system shut down.

I didn't take long before I found the reason. My DSDT was making a conflict with the system.
(I don't know why. It worked very well even from Yosemite to Catalina.)

So, I searched some developers' works and finally found yours.
After replacing my DSDT with your SSDT and patches, my system was working great even when the eGPU was connected.

![IMG_20200823_1251558_Original](https://user-images.githubusercontent.com/70421019/91873708-5276b080-ecb4-11ea-8ecc-dc1ae0defc7e.jpeg)

So, I want to say thank you for it!
Unless you uploaded them, I can't boot it up on Big Sur.

And sorry to say it suddenly, I have something to ask you.
I hope to make my material - such as my EFI partition - public for others to refer to.
But since I'm using your SSDT now, it will be very rude to you if I proceed with carelessly.
That is why I would like to ask you for permission to upload my EFI.

Thank you again for sharing your data,
and I hope each other will produce positive results for the development of X230.

Yours sincerely,

lese9855

**Comment by banhbaoxamlan** [comment]
Wow, thanks for use my EFI :heart_eyes:
It's free :relaxed:, so u can public if u want

**Comment by banhbaoxamlan** [comment]
I haven't eGPU for test it work with hackintosh, it work like on windows?

**Comment by lese9855** [comment]
Thank you for allowing me to use your SSDTs for uploading my files!

As for eGPU, pretty sure, it works flawlessly.
I'm using Radeon RX580 with Corsair HX750(PSU) since macOS 10.14 Mojave.


![IMG_20200902_1058223_Original](https://user-images.githubusercontent.com/70421019/91923977-98f7f980-ed0c-11ea-819c-3d7cae8527ee.jpeg)


In my experience, it works fine without changing any settings in EFI.
(Technically, when using Radeon Vega 64, I touched the settings a bit. However, since it was a Clover problem, I think OpenCore won't matter.)


![Screen Shot 2020-09-02 at 10 59 00 AM](https://user-images.githubusercontent.com/70421019/91924389-8205d700-ed0d-11ea-97ac-d446fa4ab1cd.png)


Both Built-In-Display and eGPU-Display are recognized normally.

**Comment by lese9855** [comment]
The resolution of Built-in Display is 12.5" FHD, cause I asked LeoKim of 51nb to modify it. - So this is not a Nitrocaster's one, but I think both methods are structurally the same.

So, I spent a lot of time modifying the EFI to use the FHD display on macOS.
I think my work will be helpful to users of the X230 with the 12.5" FHD mod ;-)

As far as I know, the 13.3" mod doesn't matter.
Since it's a simple operation using a DP port, the installation of macOS is possible without EFI modification.

**Comment by jackhu9527** [comment]
> The resolution of Built-in Display is 12.5" FHD, cause I asked LeoKim of 51nb to modify it. - So this is not a Nitrocaster's one, but I think both methods are structurally the same.
> 
> So, I spent a lot of time modifying the EFI to use the FHD display on macOS.
> I think my work will be helpful to users of the X230 with the 12.5" FHD mod ;-)
> 
> As far as I know, the 13.3" mod doesn't matter.
> Since it's a simple operation using a DP port, the installation of macOS is possible without EFI modification.

Exciting to see the X230 works great with Big Sur! I have a X230T and it is now running Catalina 10.5.7, also I tried to upgrade to Big Sur but no success. Would really appreciate it if you can share the EFI folder that works for you, thanks.:)

**Comment by lese9855** [comment]
> > The resolution of Built-in Display is 12.5" FHD, cause I asked LeoKim of 51nb to modify it. - So this is not a Nitrocaster's one, but I think both methods are structurally the same.
> > So, I spent a lot of time modifying the EFI to use the FHD display on macOS.
> > I think my work will be helpful to users of the X230 with the 12.5" FHD mod ;-)
> > As far as I know, the 13.3" mod doesn't matter.
> > Since it's a simple operation using a DP port, the installation of macOS is possible without EFI modification.
> 
> Exciting to see the X230 works great with Big Sur! I have a X230T and it is now running Catalina 10.5.7, also I tried to upgrade to Big Sur but no success. Would really appreciate it if you can share the EFI folder that works for you, thanks.:)

Sorry for the late reply, and thank you for your interest in my work.
Currently, I am working on my own EFI based on 'OpenCore 0.6.2'.
I'm putting the finishing touches on the work, so I will upload it soon.

Speaking of Big Sur, it is a very heavy operation system.
I installed it on two X230 tablet models.
The first was a model using i7-3520M, and I felt that the performance in Big Sur was very poor so that it was difficult to use. - Even though it's the best spec of the X230T.

And I installed it on the model using i7-3612QE second. - Yes, this is the modded one using 'Quad-Core'.
As a result, it was possible to use Big Sur normally only with this level of performance.

So if you want to install 'Big Sur' for everyday use on a typical(non-modded) X230, I won't recommend it. 😢

**Comment by jackhu9527** [comment]
Thanks for your response, and I really appreciate it. X230/T was and maybe
still is a great machine, but its hardware seems unable to handle the
latest OS well enough. Although it's possible to upgrade the model with an
i7-3612QE which costs $ 200, it's just too expensive and doesn't make too
much sense when newer models with 8th-gen Intel CPU only cost $600 these
days. I guess I will stay with Catalina which works fine for me.
Thanks again and I look forward to your own EFI.:)

**Comment by truongvantuan** [comment]
Cảm ơn gói EFI của bạn nhé, mình dùng trên t430 thê vài tinh chỉnh chạy rất tốt. Các static patch đúng cho máy của mình, muốn từ chuyển qua hot patch nhưng không biết cách. [https://github.com/drasbeck/macos-thinkpad-t430/blob/master/high-resolution-dsdt-patch.txt](https://github.com/drasbeck/macos-thinkpad-t430/blob/master/high-resolution-dsdt-patch.txt)
Nhờ bạn xem qua ở link trên, rồi chỉ giúp mình tóm lược các ý để mình có thể tự làm được không. Mình cám ơn.

**Comment by jamesfawcett** [comment]
> > > The resolution of Built-in Display is 12.5" FHD, cause I asked LeoKim of 51nb to modify it. - So this is not a Nitrocaster's one, but I think both methods are structurally the same.
> > > So, I spent a lot of time modifying the EFI to use the FHD display on macOS.
> > > I think my work will be helpful to users of the X230 with the 12.5" FHD mod ;-)
> > > As far as I know, the 13.3" mod doesn't matter.
> > > Since it's a simple operation using a DP port, the installation of macOS is possible without EFI modification.
> > 
> > 
> > Exciting to see the X230 works great with Big Sur! I have a X230T and it is now running Catalina 10.5.7, also I tried to upgrade to Big Sur but no success. Would really appreciate it if you can share the EFI folder that works for you, thanks.:)
> 
> Sorry for the late reply, and thank you for your interest in my work.
> Currently, I am working on my own EFI based on 'OpenCore 0.6.2'.
> I'm putting the finishing touches on the work, so I will upload it soon.
> 
> Speaking of Big Sur, it is a very heavy operation system.
> I installed it on two X230 tablet models.
> The first was a model using i7-3520M, and I felt that the performance in Big Sur was very poor so that it was difficult to use. - Even though it's the best spec of the X230T.
> 
> And I installed it on the model using i7-3612QE second. - Yes, this is the modded one using 'Quad-Core'.
> As a result, it was possible to use Big Sur normally only with this level of performance.
> 
> So if you want to install 'Big Sur' for everyday use on a typical(non-modded) X230, I won't recommend it. 😢

@lese9855 do you have a repo for your EFI with the quad core X230? I have ordered one from China with a  i7-3615QE and will be making it a hackintosh. I don't really like Big Sur but will give it a go. Did you downgrade back to Catalina?

**Comment by mrfiskare** [comment]
@jamesfawcett @lese9855 Did you experience any problems with Big Sur other than it's running slow?

**Comment by WigHlod** [comment]
I'm really happy to se a x230t run on that setup.. in few days is gonna me to :)
