### ISSUE TITLE
my x230 boot error 0251

### ISSUE THREAD

**Issue by realonnne** [banhbaoxamlan/X230-Hackintosh#13]
I got your efi to my x230. When I reboot my x230.It will show 0251 system cmos checksum bad.Can U help me to solve this problem? THX

**Comment by realonnne** [comment]
When I use your clover efi for mojave,this will not happen.But when I use your opencore efi for catalina,the checksum errors will happen.My bios setting was not changed.

**Comment by banhbaoxamlan** [comment]
If u use clover before, u should clean nvram

**Comment by realonnne** [comment]
I use OC to reset the nvram,but the problem remains

**Comment by 13631181823** [comment]
maby u can try to use clover's uefishell(or add a uefi shell.efi tool in oc boot) to input:_dmpstore -d -all_to clean all nvram .have a try.

**Comment by realonnne** [comment]
I use this method to clean all nvram,but the problem remains

**Comment by notfrommalaysia** [comment]
yes, can confirm that the same issue happens to me. i've used clover on this laptop before, already tried reset nvram but the error 0251 keeps coming back.

For the record, i have the old installation (sierra) with clover on my msata ssd, the new installation (catalina) on my sata ssd. just in case it does relates. please advise, thanks!

**Comment by realonnne** [comment]
Kernel-Quirks-Enable DisableRtcChecksum，The error has gone

**Comment by notfrommalaysia** [comment]
The issue is solved, thank you very much!
