### ISSUE TITLE
Bluetooth  can not work

### ISSUE THREAD

**Issue by jvuixcqm** [banhbaoxamlan/X230-Hackintosh#16]
I also use the 94360 wireless network card, why does my Bluetooth  can not work, is there any way to solve this problem？

**Comment by 13631181823** [comment]
have u √ the options？Bluetooth. kext there just add but not √。

**Comment by jvuixcqm** [comment]
> have u √ the options？Bluetooth. kext there just add but not √。

I will √ them now, but I am not sure which one need to √
1AirportBrcmFixup.kext
2BrcmBlueboothInjector.kext
3BrcmFirmwareData.ketx
4BrcmPatchRAM3.kext
5BlueTooth_BCM.kext

**Comment by 13631181823** [comment]
> > have u √ the options？Bluetooth. kext there just add but not √。
> 
> I will √ them now, but I am not sure which one need to √
> 1AirportBrcmFixup.kext
> 2BrcmBlueboothInjector.kext
> 3BrcmFirmwareData.ketx
> 4BrcmPatchRAM3.kext
> 5BlueTooth_BCM.kext

try √ all if you happy to😁

**Comment by Automata02** [comment]
Check if the kexts are in correct order:
1)AirportBrcmFixup
2)BrcmBluetoothInjector
3)BrcmFirmwareData
4)BrcmPatchRam3
If they're in the wrong order bt will not work. Check if the kexts are enabled (set to true), check if your USB map is working as Bluetooth functionality requires it. **You only need those 4 kexts** for that specific wireless card. I have the same one (AW-CB160H to be exact) and it works with no issues.

**Comment by banhbaoxamlan** [comment]
U need to cut or tap over pin 51 on the card.
