### ISSUE TITLE
开机会报错0251: System CMOS Checksum bad - Default configuraton used. 

### ISSUE THREAD

**Issue by jvuixcqm** [banhbaoxamlan/X230-Hackintosh#17]
我用了一块硬盘用OC只安装了黑苹果，这种情况下，每次开机都会提示0251：System CMOS Checksum bad；但是我再安装一块安装有win10系统的硬盘就可以直接开机，没有报错，重启或者关机再开机都没有；两块硬盘共存的情况下，也是开启win没问题，mac就报错。
![41601821408_ pic_hd](https://user-images.githubusercontent.com/32917717/95018142-4f465a00-0690-11eb-8520-833022548c41.jpg)

**Comment by jvuixcqm** [comment]
看到前面的问题了，应该是解决了，我试试。
![51601822102_ pic_hd](https://user-images.githubusercontent.com/32917717/95018378-e9f36880-0691-11eb-90ae-63a754491005.jpg)

**Comment by 13631181823** [comment]
随缘了哈哈哈，不勾选我也不会出现

**Comment by 13631181823** [comment]
我没有刷bios不会出现，而后才会。
