### ISSUE TITLE
开机过程中显示OCS:界面

### ISSUE THREAD

**Issue by jvuixcqm** [banhbaoxamlan/X230-Hackintosh#18]
系统内的OCC软件升级了个版本，然后电脑在开机过程中就会闪过一个界面，如下图，有没有办法不显示呢？

![image](https://user-images.githubusercontent.com/32917717/95575599-8e462800-0a61-11eb-9f6d-ab0ceefaeee5.png)

**Comment by jvuixcqm** [comment]
我又自己解决了，把OCC版本退回去，然后把onfig文件再保存一下重启就没了

**Comment by 13631181823** [comment]
编辑器要对应oc版本🦆兄弟。

**Comment by jvuixcqm** [comment]
> 编辑器要对应oc版本🦆兄弟。

新手新手，莫怪

**Comment by 13631181823** [comment]
> > 编辑器要对应oc版本🦆兄弟。
> 
> 新手新手，莫怪

x230大家一起玩黑果🌝🌝

**Comment by jvuixcqm** [comment]
> > > 编辑器要对应oc版本🦆兄弟。
> > 
> > 
> > 新手新手，莫怪
> 
> x230大家一起玩黑果🌝🌝

来X230DIY群玩耍啊，q群630870967

**Comment by matthew-dong001** [comment]
怎么入群是拒绝的

**Comment by matthew-dong001** [comment]
> > > > 编辑器要对应oc版本🦆兄弟。
> > > 
> > > 
> > > 新手新手，莫怪
> > 
> > 
> > x230大家一起玩黑果🌝🌝
> 
> 来X230DIY群玩耍啊，q群630870967

入群是不能进入的
