### ISSUE TITLE
Fualt CR2 :0xff......,error code:0x0000000 fault cpu :0x0

### ISSUE THREAD

**Issue by altercyx** [banhbaoxamlan/X230-Hackintosh#19]
i don't kown why ,my config not work

- [x] SMBIOS is set

- [x] SSDT-PM.aml is set too
 
i colsed cfg lock config

and it just doest work ~~

OS 10.15.7
macOS Catalina 版本10.15.7（版号19H2）
I installed it with clover ~

can anyone help me ,thanks

![image](https://user-images.githubusercontent.com/4946413/96128869-74f12000-0f28-11eb-9f75-afb6d6144a9d.png)

and config.plist
Config.plist

[Config.plist.zip](https://github.com/banhbaoxamlan/X230-Hackintosh/files/5384969/Config.plist.zip)

**Comment by 13631181823** [comment]
ssd-pm是否是你的cpu生成的呢？

**Comment by 13631181823** [comment]
内核驱动千万不要加io802family驱动网卡

**Comment by altercyx** [comment]
> 内核驱动千万不要加io802family驱动网卡

1 是自己生成的啦，  2 没有添加原EFI驱动以外的东西
