### ISSUE TITLE
in memory panic need help。

### ISSUE THREAD

**Issue by 13631181823** [banhbaoxamlan/X230-Hackintosh#2]
![Screenshot_2020-08-22-08-31-30-960_com mxtech videoplayer pro](https://user-images.githubusercontent.com/53339278/90944549-088b0080-e452-11ea-9db3-d5a22f0506c7.jpg)

**Comment by 13631181823** [comment]
ssdt.aml =ssdt-pm.aml

**Comment by 13631181823** [comment]
First of all, thank you very much for your hard work. I am very glad to help you with the test. But I wonder if you have a better contact?
WeChat，WhatsApp，telegram？

**Comment by banhbaoxamlan** [comment]
> ssdt.aml =ssdt-pm.aml

Sorry I will note it in README

> First of all, thank you very much for your hard work. I am very glad to help you with the test. But I wonder if you have a better contact?
> WeChat，WhatsApp，telegram？

I used Telegram : +84867450107
