### ISSUE TITLE
trackpad scrolling with two fingers low responsive on x230t - tablet

### ISSUE THREAD

**Issue by sergvax** [banhbaoxamlan/X230-Hackintosh#20]
trackpad scrolling with two fingers is low responsive on x230t - tablet

And cursor moving with trackpad also slow and feel gummy, changing system preferences not helped

**Comment by mave-panda** [comment]
Try raising the acceleration. It helps a lot

**Comment by sergvax** [comment]
I actually did find out what is wrong with trackpad on my x230t  - 

it have deadzones around 50mm each side - where it is not respond on touches and scrolling,
so small trackpad became even more smaller 

but in windows no deadzones and it works fine

I think it should be possible to remove dedzones with 
VoodooPS2Controller.kext
but I don't know how

**Comment by k4kanwar** [comment]
Any solutions to this yet??

**Comment by jamesfawcett** [comment]
I have the same issue. If I disable SSDT-KBD.aml the full touchpad will work, the the trackpoint is jerky. 

I have played around with all the settings inside SSDT-KBD.aml (also known as SSDT-Thinkpad_Trackpad.aml on other repos) but I can't solve it.

Ps - increasing the ScrollResolution within the aml file increases the two finger scrolling to a better level.

**Comment by k4kanwar** [comment]
@jamesfawcett how do you edit the aml files

**Comment by Jan-E** [comment]
Install MaciASL: https://github.com/acidanthera/MaciASL/releases

**Comment by k4kanwar** [comment]
What is the reason for enabling SSDT KBD if the trackpad and trackpoint work well without it?? any idea @banhbaoxamlan @jamesfawcett 

I just disabled it and the trackpad is working amazingly now.

**Comment by jamesfawcett** [comment]
> What is the reason for enabling SSDT KBD if the trackpad and trackpoint work well without it?? any idea @banhbaoxamlan @jamesfawcett 
> 
> 
> 
> I just disabled it and the trackpad is working amazingly now.

But is your track point jerky now? Is it still smooth?

Without this aml, my track point is unusable. I do most of my work with the track point.
