### ISSUE TITLE
hdd, usb, network -  boot options disappeared in bios on x230t - tablet

### ISSUE THREAD

**Issue by sergvax** [banhbaoxamlan/X230-Hackintosh#21]
after selecting - reset nvram - boot options in !bios! disappeared
hdd, usb, network -  boot options disappeared in bios on x230t - tablet
and only one option here is - opencore

**Comment by 13631181823** [comment]
maybe this problem occur from oc.
u can reset bios and than lock the boot order .
this could  help to reset nvram , they will  not disappear.🌚🌚
