### ISSUE TITLE
windows boot entry not work from opencore on x230t - tablet

### ISSUE THREAD

**Issue by sergvax** [banhbaoxamlan/X230-Hackintosh#22]
after "nvram reset" - 
windows boot entry not work from opencore on x230t - tablet
when try to boot it show blue screen error - ''ACPI BIOS ERROR"

**Comment by 13631181823** [comment]
try to  boot again can fix it?

**Comment by FIndustries** [comment]
I have the same issue on x230. It works perfectly from Clover. I've tried multiple times but with no luck.

**Comment by oranggila** [comment]
windows 10 boot error try disable SSDT-SDC.aml it works for me, but motherboard become acidthera, if I boot from F12 bios not from OpenCore motherboard normal become Lenovo again
