### ISSUE TITLE
Black screen after picker

### ISSUE THREAD

**Issue by caydin5** [banhbaoxamlan/X230-Hackintosh#24]
Hello,

First off, I want to thank you so much for making this available for everyone. I had an attempt at installing this on my x230 but I could not get past the booting process for installing.

I’m guessing it is related to the mods I made on my x230. 

Here are the specs:
13.3 FHD
i7 3612qe
16 GB RAM
No keyboard mod

I tried adding SSDT-EC-LAPTOP and tweaked some stuff in the config file including bootargs with no results.

Loading progresses fine up to some point where the screen goes black.

I’m thinking it is either related to the FHD or the CPU. Is there any way I can get this to work?

You can find the boot log as an attachment.

Any help is appreciated.

[opencore-2020-10-28-224436.txt](https://github.com/banhbaoxamlan/X230-Hackintosh/files/5455874/opencore-2020-10-28-224436.txt)

**Comment by caydin5** [comment]
I just confirmed that it is the FHD preventing me from seeing anything. Connected to my monitor using DP and all is well. Any workarounds to get the FHD working?

**Comment by jamesfawcett** [comment]
Hello how is your hard drive currently partitioned and what formats do you have set?

**Comment by jamesfawcett** [comment]
Oh sorry I replied to first I didn't see your update 👍

**Comment by caydin5** [comment]
No worries :) Just want to know if it's possible to install macOS on a 1080p modded x230. I've seen some successful ones out there using opencore so I'm hoping they can share their insight :)

**Comment by jvuixcqm** [comment]
> 不用担心:)只想知道是否可以在1080p改装的x230上安装macOS。我已经看到一些使用opencore的成功案例，希望他们可以分享他们的见解:)

It is possible to modify the screen at 1080p, my x230 is modified with a 13.3-inch Sharp screen, macos 10.15.7 works well

**Comment by caydin5** [comment]
> > 不用担心:)只想知道是否可以在1080p改装的x230上安装macOS。我已经看到一些使用opencore的成功案例，希望他们可以分享他们的见解:)
> 
> It is possible to modify the screen at 1080p, my x230 is modified with a 13.3-inch Sharp screen, macos 10.15.7 works well

That's great to hear. Mind sharing your EFI? Maybe there's something wrong with my setup.

**Comment by banhbaoxamlan** [comment]
With 1600 by 900 displays or higher, use AAPL,ig-platform-id `04006601`.
