### ISSUE TITLE
过几天要升级11吗？

### ISSUE THREAD

**Issue by jvuixcqm** [banhbaoxamlan/X230-Hackintosh#26]
大佬过几天要升级11吗？

**Comment by 13631181823** [comment]
我现在11.01rc版本，使用基本ok，就是机器老了，感觉有时候不如win10 2009香了。

**Comment by matthew-dong001** [comment]
> 我现在11.01rc版本，使用基本ok，就是机器老了，感觉有时候不如win10 2009香了。

你的x230已经升级到11了吗

**Comment by 13631181823** [comment]
> > 我现在11.01rc版本，使用基本ok，就是机器老了，感觉有时候不如win10 2009香了。
> 
> 你的x230已经升级到11了吗

现在用11rc2，明天等正式版！没有问题！

**Comment by matthew-dong001** [comment]
> > > 我现在11.01rc版本，使用基本ok，就是机器老了，感觉有时候不如win10 2009香了。
> > 
> > 
> > 你的x230已经升级到11了吗
> 
> 现在用11rc2，明天等正式版！没有问题！
11不是对硬盘有要求的你是什么牌子的msata，方便加你qq或者微信吗

**Comment by matthew-dong001** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "banhbaoxamlan/X230-Hackintosh"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月12日(星期四) 上午8:16
收件人:&nbsp;"banhbaoxamlan/X230-Hackintosh"<X230-Hackintosh@noreply.github.com&gt;;
抄送:&nbsp;"董权"<642859794@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [banhbaoxamlan/X230-Hackintosh] 过几天要升级11吗？ (#26)





   
我现在11.01rc版本，使用基本ok，就是机器老了，感觉有时候不如win10 2009香了。
  
你的x230已经升级到11了吗
  
现在用11rc2，明天等正式版！没有问题！
