### ISSUE TITLE
Wifi Issues - BCM94352HMB

### ISSUE THREAD

**Issue by FIndustries** [banhbaoxamlan/X230-Hackintosh#27]
Hi,
first of all I would like to thank you for this project. 
The system is truly stable and works almost flawlessly with very little effort.

I am having some problems with the wifi card AW-CE123H ( BCM94352HMB ). With Clover it was working perfectly but I can't get it to work with OpenCore.

I've followed the [instructions](https://github.com/banhbaoxamlan/X230-Hackintosh/tree/master/Other/Modifications/Wireless) but it is still undetected. 
I've already set the recommended BIOS settings (with modded bios), I've added the SSDT-PM.aml, I've ran USBMap and updated the Kext but still nothing.

My system is a X230 stock with only modded bios and new wifi card.

**Comment by dustojnikhummer** [comment]
I also have a CE123H. All I needed to do is to use the "Clean OC snapshot" thing in ProperTree. It autopopulates the Config.plist based on what kexts you have. Try that.

**Comment by FIndustries** [comment]
Thank you so much! The WiFi is now working perfectly!

**Comment by ghost** [comment]
I got the Airdrop and Bluetooth to work with efi for my one on Monterey 12.6 

https://github.com/pil4/m93p-tiny-hackintosh

**Comment by dustojnikhummer** [comment]
> I got the Airdrop and Bluetooth to work with efi for my one on Monterey 12.6
> 
> https://github.com/pil4/m93p-tiny-hackintosh

Hold on a minute, Montenery? On an X230??
