### ISSUE TITLE
Bluetooth can not work Bluetooth can not work

### ISSUE THREAD

**Issue by ballhtml** [banhbaoxamlan/X230-Hackintosh#28]
Hi,
first of all I would like to thank you for this project.
The system is truly stable and works almost flawlessly with very little effort.
My system is a X230 stock with only modded bios ver 2.74 and new wifi card.
I am having some problems with the wifi card Bluetooth can not work
not work for me I've already set the recommended BIOS settings 
I will √ them now 
1 AirportBrcmFixup.kext
2 BrcmBlueboothInjector.kext
3 BrcmFirmwareData.ketx
4 BrcmPatchRAM3.kext
5 BlueTooth_BCM.kext
Bluetooth can not work

**Comment by BlvckBytes** [comment]
What exact card model have you got installed in your system?

**Comment by ballhtml** [comment]
> What exact card model have you got installed in your system?

AW-CB160H BCM94360HMB

**Comment by dustojnikhummer** [comment]
Do you have the stock BT board connected? It is that small weird PCB under the palmrest. That one works in MacOS (while the stock WiFi card does not) and it might interfere. Try taking it out first.

**Comment by ballhtml** [comment]
> Do you have the stock BT board connected? It is that small weird PCB under the palmrest. That one works in MacOS (while the stock WiFi card does not) and it might interfere. Try taking it out first.
----------------------------------------------------------------------------------
I removed the original BT, only the AW-CB160H BCM94360HMB left. As for the cable, I was able to connect only the one from the newly purchased adapter.

**Comment by dustojnikhummer** [comment]
> > Do you have the stock BT board connected? It is that small weird PCB under the palmrest. That one works in MacOS (while the stock WiFi card does not) and it might interfere. Try taking it out first.
> 
> I removed the original BT, only the AW-CB160H BCM94360HMB left. As for the cable, I was able to connect only the one from the newly purchased adapter.

Cable is just an antenna. Without it it will work, though with a range of about 1 meter.

**Comment by banhbaoxamlan** [comment]
Cutting or taping over pin 51 on the card

**Comment by banhbaoxamlan** [comment]
> Hi,
> first of all I would like to thank you for this project.
> The system is truly stable and works almost flawlessly with very little effort.
> My system is a X230 stock with only modded bios ver 2.74 and new wifi card.
> I am having some problems with the wifi card Bluetooth can not work
> not work for me I've already set the recommended BIOS settings
> I will √ them now
> 1 AirportBrcmFixup.kext
> 2 BrcmBlueboothInjector.kext
> 3 BrcmFirmwareData.ketx
> 4 BrcmPatchRAM3.kext
> 5 BlueTooth_BCM.kext
> Bluetooth can not work

First, you need cutting or taping over pin 51 on the card.
For Bluetooth, you need 3 kexts:
> 2 BrcmBlueboothInjector.kext
> 3 BrcmFirmwareData.ketx
> 4 BrcmPatchRAM3.kext

and

> 5 BlueTooth_BCM.kext

Only for stock BT

**Comment by sergvax** [comment]
I updated to last commit and stock bluetooth on my x230t now working!
