### ISSUE TITLE
Trackpoint and buttons above trackpad not recognized

### ISSUE THREAD

**Issue by BlvckBytes** [banhbaoxamlan/X230-Hackintosh#29]
Hello!

Thanks a lot for this repo, helped me to save a ton of time. Only one issue so far: The trackpoint and the three buttons above the trackpad are not working, at all. There is a kext from tluck (https://github.com/tluck/OS-X-Voodoo-PS2-Controller) which works, but it messes up the trackpad accuracy and the trackpoint is moving very chunkily.

I've seen that there are some SSDTs where parameters could be changed. But you've stated that your trackpoint works perfectly, so... any ideas why mine's not working? I updated all other kexts and OC, minor config adjustments, got rid of ALS-related stuff aswell as UIAC and WIFI, as I don't need them (UIAC is made obsolete by USB-kext and my WIFI is dead). But since it works with the kext from the provided link above, I think this has nothing to do with it. It just works pretty bad, like it's not optimized/configured to my model.

Attached my current EFI.
Would be appreciative of all help, thanks in regards!
[EFI.zip](https://github.com/banhbaoxamlan/X230-Hackintosh/files/5519539/EFI.zip)

**Comment by jamesfawcett** [comment]
Hi @BlvckBytes please can you try this release of VooDooPS2Controller, any later than this version I had the same issues https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller/releases/tag/v1.8.2

**Comment by BlvckBytes** [comment]
@jamesfawcett 

Hey there! Thanks a lot for your response. So, by v1.8.2 you mean the kext that got released on Apr 7th, 2013? Didn't want to compile myself, so I downloaded it from the archive: https://code.google.com/archive/p/os-x-voodoo-ps2-controller/downloads

This kext wouldn't let me boot, for some reason. Are you running the *same* on Catalina, and are you also using VirtualSMC instead of FakeSMC? Just making sure.

// Edit:
Oh, and anything I need to do with the daemon executable in the Release/ folder?
Just stuck kinda forever on AppleKeyStore operation failures. Which kind of reminded me of the whole SMC stuff.

**Comment by jamesfawcett** [comment]
Oh that's interesting to know! I have an older machine mines an X201, but it's accurate for me and two finger scrolling work. I keep all my kexts up to date but yes I'm still on 2013 VoodooPS2 :/ I have yet to convert X230 to a hackintosh I'm going to give it a go when Big Sur is released soon which is why I'm watching this repo!

**Comment by BlvckBytes** [comment]
@jamesfawcett 

Big Sur would work on a machine like this? I've read on dortania that Big Sur dropped Ivy Bridge support, and I'd say that it'd be hard to have a stable system without it, lol. Is there a workaround?

**Comment by BlvckBytes** [comment]
Found out that they didn't actually drop the support a few days ago and you just need to bump up the SMBIOS. Works for me, just can't get Bluetooth to work, but that's another topic.

**Comment by banhbaoxamlan** [comment]
I have updated new SSDT-KBD.aml, now all work correct (include wake after sleep).
