### ISSUE TITLE
SD card reader?

### ISSUE THREAD

**Issue by codic12** [banhbaoxamlan/X230-Hackintosh#31]
Why does the .aml patch to disable the richo card reader exist? I have a patched VoodooSDHC to make it work so is it safe to delete?

**Comment by banhbaoxamlan** [comment]
If u want use SD Card Reader, u can disable SSDT-SDC.aml patch in config

**Comment by oranggila** [comment]
@codic12 can you share the patched voodooSDHC, I will try to my x230

**Comment by codic12** [comment]
The patch is not functional, I was mistaken. hackintoshing is a total PITA, I've given up and gone back to Linux as I always have because macOS is a crappy resource hog. Buf if you're interested, I found this patch here: https://www.dropbox.com/s/z1xdji82wbodn23/VoodooSDHC.kext.zip?dl=0
