### ISSUE TITLE
windows acpi error & touch screen support on Big Sur

### ISSUE THREAD

**Issue by jackhu9527** [banhbaoxamlan/X230-Hackintosh#34]
Hi there. I have both Catalina 10.15.7 and Windows 10 installed on my X230 tablet. Currently I'm using Clover to dual boot the two systems without any issue, but I intend to switch to Opencore so it's possible for the tablet to be upgraded to Big Sur. After I have replaced the original Clover EFI with the OC EFI folder downloaded from this site, an upgrade from existing Catalina to Big Sur was successful, but not without two issues:

1. Windows 10 failed to boot and instead just showed the classic blue screen where it says ACPI error. I wonder what modification to the OC EFI folder is needed exactly to get Windows boot back to normal? For now my temporary solution is to press F12 and choose Windows boot manager to boot into Windows 10.
2. The model I'm currently using is an X230T, which is almost the same as X230 in terms of hardware but with a smaller touch screen. Touch screen support on Catalina was almost perfect with the previous Clover EFI that I have, as both finger touch and stylus were well supported. After the system upgrade to Big Sur,  during the setup process of the 1st boot, I was still able to use my finger as touch on the screen and move the mouse. The second this setup process was finished, the screen stopped responding, both my fingers and the stylus didn't work as before. It's just weird.
Thanks for any constructive feedback.

**Comment by dqwfgzs** [comment]
I have the similar problem too. My device is a X230 with the same hardware, and while I boot Windows with OpenCore, it also cause the same ACPI error bluescreen. Recently I found some solutions and they said that the SSDT need to be patched with the patch that can "tell" OpenCore these SSDTs are used with macOS only, and while using Windows, they would not work yet.

**Comment by shimingyun** [comment]
Disable with SSDT-SDC.aml Win10 is yes!
