### ISSUE TITLE
Watching this repo, ordered modded X220!

### ISSUE THREAD

**Issue by jamesfawcett** [banhbaoxamlan/X230-Hackintosh#37]
Just a message to say thanks for this repo, I've been watching now for over 6 months! I've finally ordered an X220 to replace my X201. I've ordered it from Taiwan we have a groupbuy in the [Thinkpad Facebook group](https://www.facebook.com/groups/ThinkPadsOldAndNew), its coming with 16:10 aspect, 13.3 inch, 2560 x 1600 350+ nits panel. I paid extra to have the dual core CPU de-soldered and replaced with quad core. It's going to be such a nice machine! 

I'm going to use your repo as a base and get mine working as a Hackintosh too.

Here is another member's X230 modded (AKA the X330): https://scontent-cdt1-1.xx.fbcdn.net/v/t1.0-9/130775223_396240841692412_7322386549935811139_n.jpg?_nc_cat=109&ccb=2&_nc_sid=b9115d&_nc_ohc=pYSpfndYlvkAX-39BG0&_nc_ht=scontent-cdt1-1.xx&oh=a0377181d13c7edc6cc2d4ae57e67e11&oe=6003A9A1

**Comment by jamesfawcett** [comment]
@banhbaoxamlan is your wifi card definitely correct in the README.md? 

`AzureWave AW-CE123H (BCM94360HMB)`

I can only find **Azurewave AW-CB160H** with the BCM94360HMB.

The AzureWave AW-CE123H has the BCM94352HMB.

I have the **Azurewave AW-CB160H** in my other X201 hackintosh, it works great but its IPEX-4 instead of IPEX-1.

Can you confirm which you have? I want to copy yours for my X330. 

Thank you

**Comment by banhbaoxamlan** [comment]
> @banhbaoxamlan is your wifi card definitely correct in the README.md?
> 
> `AzureWave AW-CE123H (BCM94360HMB)`
> 
> I can only find **Azurewave AW-CB160H** with the BCM94360HMB.
> 
> The AzureWave AW-CE123H has the BCM94352HMB.
> 
> I have the **Azurewave AW-CB160H** in my other X201 hackintosh, it works great but its IPEX-4 instead of IPEX-1.
> 
> Can you confirm which you have? I want to copy yours for my X330.
> 
> Thank you

Sorry, I edited it <3, I used AW-CE123H, waiting for AW-CB160H :((

**Comment by jamesfawcett** [comment]
The AW-CE123H works perfectly! 

Also, your repo and instructions were EXACTLY what I needed. My X330 is now Hackintoshed, and I generated the SSDT-PM.aml.

I am just upgrading from Catalina to Big Sur now. There was one issue with the Wifi card during upgrade, Big Sur wouldn't upgrade with it installed. But removing the wifi card fixed the issue. 

It's now updated to Big Sur no problem :)
