### ISSUE TITLE
win10蓝屏问题解决方案

### ISSUE THREAD

**Issue by shimingyun** [banhbaoxamlan/X230-Hackintosh#38]
禁用SSDT-SDC.aml 就可以进入win10了，要不转半圈蓝屏。请问下SSDT-SDC 是干什么用的？我禁用后也没发现异常。

**Comment by 13631181823** [comment]
是用来禁用sd卡读卡器的🌝，，谢谢分享。

**Comment by banhbaoxamlan** [comment]
Disable SSDT-SDC.aml
