### ISSUE TITLE
Got stuck on EXITBS

### ISSUE THREAD

**Issue by medkintos** [banhbaoxamlan/X230-Hackintosh#4]
Hello, trying your config to run on my X230 to install Catalina. After picking the Installer partition, it spits the EXITBS error even before the macOS loads:

> 00:000 00:000 AAPL: [EB|#LOG:INIT] 2020-08-22T23:49:42
> 00:029 00:029 AAPL: [EB|#VERSION] bootbase.efi 422.120.8~3 (Official), built 2020-04-25T13:24:41-0700
> 00:058 00:029 AAPL: [EB|#BUILD] BUILD-INFO[306]:{"DisplayName":"bootbase.efi","DisplayVersion":"422.120.8~3","RecordUuid":"66066909-B30A-4C33-9E16-6BEC64D1BB3D","BuildTime":"2020-04-25T13:24:41-0700","ProjectName":"efiboot","ProductName":"bootbase.efi","SourceVersion":"422.120.8","BuildVersion":"3","BuildConfiguration":"Release","BuildType":"Official"}
> 00:090 00:032 AAPL: [EB|#H:IS] 0
> 00:119 00:029 AAPL: [EB|#WL:MODE] 0
> 00:148 00:029 AAPL: [EB|#CONFIG:SRC] <default>
> 00:186 00:037 AAPL: [EB|#CONFIG| 0] boot-save-log : 0x0000000000000002 (0x0000000000000002 < 0xFFFFFFFFFFFFFFFF) <default>
> 00:228 00:041 AAPL: [EB|#CONFIG| 1] wake-save-log : 0x0000000000000002 (0x0000000000000002 < 0x0000000000000002) <default>
> 00:257 00:029 AAPL: [EB|#CONFIG| 2] console       : 0x0000000000000001 (0x0000000000000001 < 0x0000000000000001) <default>
> 00:286 00:029 AAPL: [EB|#CONFIG| 3] serial        : 0x0000000000000000 (0x0000000000000000 < 0x0000000000000000) <default>
> 00:318 00:032 AAPL: [EB|#CONFIG| 4] embed-log-dt  : 0x0000000000000000 (0x0000000000000000 < 0x0000000000000000) <default>
> 00:361 00:042 AAPL: [EB|#CONFIG| 5] timestamps    : 0x0000000000000000 (0x0000000000000000 < 0xFFFFFFFFFFFFFFFF) <default>
> 00:390 00:028 AAPL: [EB|#CONFIG| 6] log-level     : 0x0000000000000001 (0x0000000000000001 & 0x0000000000000001) <default>
> 00:420 00:029 AAPL: [EB|#CONFIG| 7] breakpoint    : 0x0000000000000000 (0x0000000000000000 & 0x0000000000000000) <default>
> 00:452 00:032 AAPL: [EB|#CONFIG| 8] kc-read-size  : 0x0000000000100000 (0x0000000000100000 < 0xFFFFFFFFFFFFFFFF) <default>
> 00:494 00:042 AAPL: [EB|#H:IS] 0
> 00:523 00:029 AAPL: [EB|#WL|0] 0x01 0x01   0 0x00
> 00:553 00:029 AAPL: [EB|#BRD:NV] Mac-AFD8A9D944EA4843
> 00:585 00:032 AAPL: [EB|#WL|1] 0x01 0x01   2 0x00
> 00:628 00:043 AAPL: [EB|#B:RRVAR] ba660466ed66
> 00:657 00:029 AAPL: [EB|#B:MLBVAR] œ
> 00:687 00:029 AAPL: [EB|`BST:IDT] {
> 00:719 00:032 AAPL: [EB|`BST:IDT] }
> 00:761 00:042 AAPL: [EB|#WL|2] 0x01 0x01   3 0x00
> 00:790 00:029 AAPL: [EB|#WL|3] 0x01 0x01   4 0x00
> 00:820 00:029 AAPL: [EB|#BRD:NV] Mac-AFD8A9D944EA4843
> 00:852 00:032 AAPL: [EB|#WL|4] 0x01 0x01   5 0x00
> 00:894 00:042 AAPL: [EB|`H:CHK] BM: 0x0000000000000000
> 00:924 00:029 AAPL: [EB|`H:CHK] Err(0xE) @ GV boot-signature
> 00:953 00:029 AAPL: [EB|#WL|5] 0x01 0x01  23 0x0E
> 00:986 00:032 AAPL: [EB|`H:CPM] Err(0xE), (24, 24) @ GV Persistent-memory-note
> 01:028 00:042 AAPL: [EB|`SB:EN] Err(0xE) @ LocP 24B73556-2197-4702-82A8-3E1337DAFBF2
> 01:058 00:029 AAPL: [EB|#LIMG:DP] Acpi(PNP0A03,0)/Pci(1A|0)/Usb(0, 0)/Usb(1, 0)/HD(Part2,Sig01B2C049-21C4-454F-90E2-7444DE223CB1)
> 01:087 00:029 AAPL: [EB|#LIMG:FP] \System\Library\CoreServices\boot.efi
> 01:119 00:031 AAPL: [EB|#LIMG:OPT] ()
> 01:161 00:042 AAPL: [EB|#RPS] R?0 P?0 S?0
> 01:191 00:030 AAPL: [EB|`OPT:LXF] 'LF (\\System\\Library\\CoreServices\\com.apple.Boot.plist)
> 01:220 00:029 AAPL: [EB|`LD:LF] FIO: 0, DIR: 1, P: \\System\\Library\\CoreServices\\com.apple.Boot.plist, DP: 0
> 01:252 00:031 AAPL: [EB|`LD:OFS] Err(0xE) @ OPEN (\\System\\Library\\CoreServices\\com.apple.Boot.plist)
> 01:294 00:042 AAPL: [EB|`OPT:LXF] Err(0xE) @ 'LF
> 01:323 00:028 AAPL: [EB|`OPT:LXF] 'LF (Library\\Preferences\\SystemConfiguration\\com.apple.Boot.plist)
> 01:353 00:029 AAPL: [EB|`LD:LF] FIO: 0, DIR: 1, P: Library\\Preferences\\SystemConfiguration\\com.apple.Boot.plist, DP: 0
> 01:434 00:081 AAPL: [EB:#KF] (root-dmg=file:///Install%20macOS%20Catalina.app/Contents/SharedSupport/BaseSystem.dmg)
> 01:464 00:029 AAPL: [EB|#MBA:CL] ()
> 01:493 00:029 AAPL: [EB|#MBA:NV] (-v)
> 01:532 00:039 AAPL: [EB|#MBA:KF] (root-dmg=file:///Install%20macOS%20Catalina.app/Contents/SharedSupport/BaseSystem.dmg)
> 01:575 00:043 AAPL: [EB|#MBA:OUT] (-v root-dmg=file:///Install%20macOS%20Catalina.app/Contents/SharedSupport/BaseSystem.dmg)
> 01:620 00:044 AAPL: [EB|#LOG:VERBOSE] 2020-08-22T23:49:44
> 01:664 00:044 AAPL: [EB|#OPT:BM] 0x4002
> 01:709 00:044 AAPL: [EB|`OPT:LXF] 'LF (\\System\\Library\\CoreServices\\PlatformSupport.plist)
> 01:753 00:044 AAPL: [EB|`LD:LF] FIO: 0, DIR: 1, P: \\System\\Library\\CoreServices\\PlatformSupport.plist, DP: 0
> 01:799 00:045 AAPL: [EB|#B:VAw]
> 01:842 00:043 AAPL: [EB|`P:DCCPR] Err(0xE) @ GV AAPL,CoProcessorReboot
> 01:887 00:044 AAPL: [EB|#P:MPI] N
> 01:931 00:044 AAPL: [EB|`CS:CSKSD] {
> 01:976 00:044 AAPL: [EB|`CS:CSKSD] Err(0xE) @ GV 8D63D4FE-BD3C-4AAD-881D-86FD974BC1DF:boot-info-payload
> 02:020 00:044 AAPL: [EB|`G:CS] } Ok(0)
> 02:064 00:044 AAPL: [EB|`LD:LF] FIO: 0, DIR: 1, P: <null string>, DP: 1
> 02:139 00:074 AAPL: [EB|`B:SBS] SZ: 617016
> 02:173 00:034 AAPL: [EB|#B:SHA] 462dad30d0060217458b69a6670eb7f6b1e5f421
> 02:202 00:029 AAPL: [EB|`WL:PWLFNV] Err(0xE) @ GV wake-failure
> 02:239 00:037 AAPL: [EB|`WL:DT] Err(0xE) @ WL:PWLFNV
> 02:284 00:044 AAPL: [EB|`WL:PWLFRTC] ! @ RTC:R
> 02:313 00:028 AAPL: [EB|`WL:DT] Err(0xE) @ WL:PWLFRTC
> 02:342 00:029 AAPL: [EB|`LD:LKC] BPDK -> (System\Library\PrelinkedKernels\prelinkedkernel.development)
> 02:375 00:032 AAPL: [EB|`LD:OFS] Err(0xE) @ OPEN (System\\Library\\PrelinkedKernels\\prelinkedkernel.development)
> 02:417 00:042 AAPL: [EB|`LD:LKC] BPDK,!R -> (System\Library\PrelinkedKernels\prelinkedkernel)
> 05:930 03:513 AAPL: [EB|`LD:LKFS] } Ok(0)
> 06:003 00:072 AAPL: [EB|`LD:LKC] } Ok(0)
> 06:033 00:029 AAPL: [EB|#FWFM] 0xFF1FFF3F
> 06:062 00:029 AAPL: [EB|#FWFT] 0xE00DE137
> 06:091 00:029 AAPL: [EB|#CSR:IN] 0x00000040
> 06:121 00:029 AAPL: [EB|#CSR:OUT] 0x00000040
> 06:189 00:068 AAPL: [EB|`BST:FBS] {
> 06:219 00:030 AAPL: [EB|`BST:FBS] BA.ADSZ: 0
> 06:258 00:038 AAPL: [EB|`BST:FBS] BA.KSDSZ: 0
> 06:298 00:039 AAPL: [EB|`B:WFDW] Err(0xE), 0 @ LocHB 71B4903C-14EC-42C4-BDC6-CE1449930E49
> 06:339 00:041 AAPL: [EB|#LOG:DT] 2020-08-22T23:49:48
> 06:369 00:029 AAPL: [EB|#LOG:EXITBS:START] 2020-08-22T23:49:48

I thought there's something wrong with the Booter quirks, playing with them and still got the same results. Checking my BIOS settings and also correct as the instructions. Maybe there's something wrong in my machine?

For BIOS, I got my laptop whitelisted by 1vyrain.

**Comment by medkintos** [comment]
got it to work now,  by enabling

Security > Memory protection > Execution Prevention > Enabled

in BIOS

**Comment by banhbaoxamlan** [comment]
> got it to work now, by enabling
> 
> Security > Memory protection > Execution Prevention > Enabled
> 
> in BIOS

Thanks, I will edit ^^
