### ISSUE TITLE
Slow and Lagging in Big Sur

### ISSUE THREAD

**Issue by oranggila** [banhbaoxamlan/X230-Hackintosh#40]
your EFI installed flawlessly in my old x230, I succeeded installed big sur 11.1
my specs is
x230
i5 - 16gb ram
ssd samsung 850evo sata 500gb 
change wifi to DW1510
everything works, except card reader, vga and finger print
but...
slow and lag even to browsing via safari or chrome
miles different than catalina was so smooth
I'm rolling back to catalina and noticed so different speed
anyway thanks for the great work, my old machine can taste the future 😂

is there any fix for that, i'll try
thx

**Comment by 13631181823** [comment]
try to disable PM.aml. let it perform maximum .

**Comment by oranggila** [comment]
ok,  I just disable SSDT-PM.aml in config.plist feel like nothing changed 😁
for browsing web its ok, acceptable, for word editing so so, for photoshop I just using windows much more faster, I'm dual booting big sur and windows 10, feels like train vs heavy loaded truck 😂

**Comment by oranggila** [comment]
strange i clean install Big Sur 11.1 again, its now acceptable smooth like the Catalina, the system became slow and lagging after I partition my primary system to install other system windows 10 and sparky linux, strange, tried install the other system on my secondary msata drive, if the system not slowing, the cause was the partition... 

will update again....

after activate PM.aml became laggy again, disable pm strange same result, this is the end of i5 ivy bridge, maybe with faster processor i7 different result, but everything works, shame the performance is not acceptable for me

**Comment by oranggila** [comment]
![IMG20210201004306](https://user-images.githubusercontent.com/1418978/106402133-1910bf80-6463-11eb-8160-a6319e2527bd.jpg)
Big Sur with PM.aml so slow

![IMG20210201005451](https://user-images.githubusercontent.com/1418978/106402187-570de380-6463-11eb-82d7-58d2b9134db7.jpg)
Big Sur with PM.aml off

![IMG20210131133900](https://user-images.githubusercontent.com/1418978/106402228-7e64b080-6463-11eb-97a9-983b2e1c3e1e.jpg)
Catalina Normal PM.aml on, so different

**Comment by oranggila** [comment]
![IMG20210203094006](https://user-images.githubusercontent.com/1418978/106685646-c91d2e80-6603-11eb-872c-a9d4bddf41eb.jpg)

fix... updated to 11.2

**Comment by oranggila** [comment]
just dont disable drop cpupm nd cpu01st in plist to get the full speed 😁

**Comment by fisforfaheem** [comment]
please help me I have x230T as well but speed is too much slower
