### ISSUE TITLE
WiFi solution for Intel WLAN

### ISSUE THREAD

**Issue by spivaktar** [banhbaoxamlan/X230-Hackintosh#41]
First of all thank you for the contribution! 

Except for the bug with trackpoint after sleep mode everything works nicely. I do believe that it is possible to solve it by trying different versions of PS/2 kexts. But I it shall be tested later. 

I would also like to share with others my experience of using OpenIntelWireless and its itlwm.kext with this EFI. It basically allows you to use macOS with stock WLAN adapter of x230 without changing it or modifying the BIOS. Just use the itlwm.kext from OpenIntelWireless and disable those kexts responsible for Broadcom wifi. Stock Broadcom bluetooth also works fine with Intel WiFi, and the speed in my case is comparable to Ubuntu and Windows (80-90 Mbps when downloading).

**Comment by sergvax** [comment]
share your plist file,  I tried  - but no wifi

**Comment by spivaktar** [comment]
@sergvax It's below. And don't forget to download [Heliport](https://github.com/OpenIntelWireless/HeliPort) app to be able to scan for available networks. That's the only way to use Intel card, but the app looks and feels pretty native. 

[Config.plist.zip](https://github.com/banhbaoxamlan/X230-Hackintosh/files/5937901/Config.plist.zip)

**Comment by sergvax** [comment]
thank you, now my native intel wifi working on x230t

**Comment by Jan-E** [comment]
The Airportitlwm.kext from https://github.com/OpenIntelWireless/itlwm/releases/tag/v1.3.0 works out-of-the-box without any need for additional software or extra config. It operates just like any Wifi adapter.
