### ISSUE TITLE
Disable trackpad?

### ISSUE THREAD

**Issue by nut573** [banhbaoxamlan/X230-Hackintosh#42]
Is there a way to disable just the trackpad in VoodooPS2 like you can on Windows? I only use trackpoint exclusively, the trackpad is too small to be practical for me anyways. 

I tried disabling it in BIOS, but that also disables the middle click button. The readme on acidanthera's VoodooPS2 page mentions a Touchpad and Keyboard Input Toggle, but it doesn't seem to work for me.

**Comment by westhom** [comment]
You could try removing the palm rest and disconnecting the ribbon cable from the trackpad, wrapping the connectors in masking tape to prevent contact. Should leave the mouse buttons active since they are connected to the keyboard.

**Comment by Karleow** [comment]
Trackpad can be disabled in bios settings with trackpoint enabled.

**Comment by Valeria** [comment]
> Trackpad can be disabled in bios settings with trackpoint enabled.

When I disable the trackpad in BIOS I lose the ability to middle click scroll. Is that fixable?

**Comment by Karleow** [comment]
Well, VoodooPS2Controller.kext(https://github.com/acidanthera/VoodooPS2)  is driving Trackpoint. I think it would be best that the develop team could do a tiny adjustment to the driver to fix this problem.

**Comment by Karleow** [comment]
Or you can check "Ignore built-in trackpad when mouse or wireless trackpad is present" in setting -> Accessibility -> Pointer Control. You still have trackpad before login, but it will be disabled because you have trackpoint plug in. (MacOS 11.2.3).
New plug in USB mouse will disable trackpoint, but a USB mouse plugged on boot up will work with trackpoint at the same time.

**Comment by Valeria** [comment]
Thanks, your "Ignore built-in trackpad when mouse or wireless trackpad is present" suggestion seems to be a decent workaround for now.

It does keep the middle click scroll working.
