### ISSUE TITLE
Solution for Card Reader

### ISSUE THREAD

**Issue by ipang-dwi** [banhbaoxamlan/X230-Hackintosh#43]
You can use it to make card reader work on x230..
https://github.com/FIRSTPLATO/cardreader-kext/blob/main/README_en.md

**Comment by lese9855** [comment]
I tested this method yesterday, but it didn't work...

For someone who will try this method, the card reader in X230 is "Ricoh PCIe SDXC/MMC Host Controller".
Vendor ID is "1180 (4480 in decimal num.)" and Product ID is "E823 (59427 in decimal num.)"

In my opinion, this reader is unlikely to be recognized in macOS.
It didn't even appear on the PCI list of Hackintool...
I had to check the vendor & product ID on Windows.
