### ISSUE TITLE
No WiFi on Windows

### ISSUE THREAD

**Issue by Cikappa2904** [banhbaoxamlan/X230-Hackintosh#44]
Hello. I have successfully installed MacOS Big Sur on my Thinkpad x230 using your EFI. I also installed Windows 10 in dual boot.
The only problem I got at the moment is that the WiFi is not working both in MacOS (but I still need to try heliport) and in Windows, if I boot from OpenCore. If I boot from the BIOS Boot Menu, the WiFi works in Windows. My understanding is that OpenCore is injecting some SSDT also on Windows, and Windows doesn't like that. Is there like a SSDT that I can remove from the EFI to make WiFi work on Windows when booting from OpenCore, without also breaking MacOS? Thanks

**Comment by leonkrischer** [comment]
Hello,

I also tried to use an Intel card for a while, and my best advice for you would be to buy a Broadcom card. It is such a hassle-free experience! Heliport or intlwm can be really finicky sometimes...
