### ISSUE TITLE
Question about SSDT-XDSM.aml

### ISSUE THREAD

**Issue by 5T33Z0** [banhbaoxamlan/X230-Hackintosh#45]
Thank you for sharing your EFI.

Doesn't this hotpatch require the renaming of "_DSM" to "XDSM" to work correctly?

**Comment by banhbaoxamlan** [comment]
> Thank you for sharing your EFI.
> 
> Doesn't this hotpatch require the renaming of "_DSM" to "XDSM" to work correctly?

We still need hotpatch, I will add it on the next release, thanks <3
