### ISSUE TITLE
Trackpoint not working after sleep

### ISSUE THREAD

**Issue by Valeria** [banhbaoxamlan/X230-Hackintosh#47]
Hello.

I've installed Catalina with the EFI from this repo and everything is working as it should, including Intel WiFi (via AirportItlwm.kext), the only issue I'm currently having is Trackpoint not working after system goes to sleep (and perhaps it moving a bit more choppier than on either Windows or Linux)

Has anyone managed to fix it?

**Comment by Karleow** [comment]
If you just need Trackpoint, disable Trackpad from BIOS can bypass this problem.

**Comment by Valeria** [comment]
That does bypass this problem, but then you end up losing the middle click to scroll function as talked in issue #42.

**Comment by mcanevet** [comment]
This guy announces "No Sleep/wake issues" with its version: https://www.reddit.com/r/hackintosh/comments/elqd6k/almost_perfect_thinkpad_x230_running_catalina/. I didn't test it though. This is the thing that annoys me the most.

**Comment by banhbaoxamlan** [comment]
> This guy announces "No Sleep/wake issues" with its version: https://www.reddit.com/r/hackintosh/comments/elqd6k/almost_perfect_thinkpad_x230_running_catalina/. I didn't test it though. This is the thing that annoys me the most.

He used Rehabman's VoodooPS2 1.9.2, u can try it

**Comment by mcanevet** [comment]
OK, I'm brand new to macOS and hackintosh stuffs so I think I have a lot to learn before being able to do this (but I'd like to...).
Anyway, when looking at VoodooPS2's git repository I found this very interesting entry in the release notes of v2.2.3:
`Added DisableDeepSleep to workaround ACPI S3 wakes on some Synaptics touchpads`.
Maybe it worth a try to upgrade to v2.2.3 before trying to downgrade to 1.9.2 (for which there is no tag anyway...).
Do you think you could upgrade this Kext to v2.2.3 or guide me how to do it?

**Comment by mcanevet** [comment]
I tried to replace the `VoodooPS2Controller.kext` with the pre-compiled one on [this message](https://github.com/acidanthera/bugtracker/issues/690#issuecomment-596350525) but somehow it does not boot at all.
I have no clue how to troubleshot this or even build a Kext by myself.

**Comment by mcanevet** [comment]
According to [this message](https://github.com/acidanthera/bugtracker/issues/690#issuecomment-596350525) the problem is due to [this commit](https://github.com/acidanthera/VoodooPS2/commit/85b9a8d5058e26529d10a5c80f76c7f666b8fd14).
It looks like there is a new [`DisableDeepSleep`]( https://github.com/acidanthera/VoodooPS2/commit/69c29bcf19f629df30a345bc5117c552c3b7f3ed) in `v2.2.3` of the driver, that, according to the code, would have the same effect then reverting the problematic commit.
Would it be possible to upgrade `VoodooPS2Controller` and set `DisableDeepSleep` to `true`, or guide me how to do it?

**Comment by mcanevet** [comment]
My investigations so far:
- Rehabman's latest version (1.9.2) works fine, but somehow AirportItlwm does not work anymore,
- Acidanthera's v2.0.0 (first version after fork from Rehabman) released artifact does not boot,
- Acidanthera's v2.0.2 (last version before the problematic commit) boots, but neither trackpad nor AirportItlwm works,
- Acidanthera's v2.2.3 should work in theory with [DisableDeepSleep](https://github.com/acidanthera/VoodooPS2/blob/master/Docs/ACPI/SSDT-DisableDeepSleep.dsl) enabled, but I couldn't make it work (everything work except Trackpoint after sleep).

Still investigating...

**Comment by banhbaoxamlan** [comment]
> My investigations so far:
> 
> * Rehabman's latest version (1.9.2) works fine, but somehow AirportItlwm does not work anymore,
> * Acidanthera's v2.0.0 (first version after fork from Rehabman) released artifact does not boot,
> * Acidanthera's v2.0.2 (last version before the problematic commit) boots, but neither trackpad nor AirportItlwm works,
> * Acidanthera's v2.2.3 should work in theory with [DisableDeepSleep](https://github.com/acidanthera/VoodooPS2/blob/master/Docs/ACPI/SSDT-DisableDeepSleep.dsl) enabled, but I couldn't make it work (everything work except Trackpoint after sleep).
> 
> Still investigating...

Update your VoodooPS2 to v2.2.3, and copy my SSDT-KBD into your EFI/OC/ACPI, try it <3
[SSDT-KBD.aml.zip](https://github.com/banhbaoxamlan/X230-Hackintosh/files/6489674/SSDT-KBD.aml.zip)

**Comment by banhbaoxamlan** [comment]
I will update it in next release

**Comment by hac4us06** [comment]
Hi did you fix the issue, I'm facing similar problems on hackintosh sequoia, after sleep trackpad doesn't work at all need to reboot to make it work again
