### ISSUE TITLE
Dock USB ports not working for Big Sur

### ISSUE THREAD

**Issue by kindofblue** [banhbaoxamlan/X230-Hackintosh#48]
Any ideas?

**Comment by banhbaoxamlan** [comment]
Did u map USB ports?

**Comment by Karleow** [comment]
I guess all these problems are related, 8086:1e26 device which connects to dock didn't show up in ioreg.

**Comment by banhbaoxamlan** [comment]
I have test my Dock, ThinkPad Mini Dock Plus Series 3 (Type 4338), all USB working (6 ports 2.0 and 3.0)

**Comment by kindofblue** [comment]
@banhbaoxamlan Probably this explains why Ultrabase Series 3 (USB 2.0) ports are not working, since it is a EHCI USB device, while yours is a XHCI device.

**Comment by Karleow** [comment]
My dock is ThinkPad Mini Dock Series 3 (Type 4337), no "Plus", USBs connect to EHCI-1. I guess the "Plus" model connects to XCHI.

**Comment by banhbaoxamlan** [comment]
> My dock is ThinkPad Mini Dock Series 3 (Type 4337), no "Plus", USBs connect to EHCI-1. I guess the "Plus" model connects to XCHI.

No, it still connects to EHC1, I have to remove it on EFI-TEST so its working
