### ISSUE TITLE
USB on thinkpad mini dock series 3 don't work in BigSur 11.2

### ISSUE THREAD

**Issue by Karleow** [banhbaoxamlan/X230-Hackintosh#49]
Thinkpad mini dock series 3, not plus, no usb 3.0. BigSur 11.2
USB works good in 10.15.5 / Clover

USB on dock connects to chip Intel 7 / C216 USB 2.0 Hub 1E26 (PCI 0, 29 - 8086:1e26).
ioreg -l list device 1e31(usb3.0) & 1e2d(usb2.0 on right front), but 1e26 not found.

Add in config.plist to fake device-id (1e26->1e2d), don't work, still not show up in ioreg -l.
<code>
```
	<key>DeviceProperties</key>
	<dict>
		<key>Add</key>
		<dict>
                         <key>PciRoot(0x0)/Pci(0x1D,0x0)</key>
			<dict>
				<key>AAPL,slot-name</key>
				<string>Internal@0,29,0</string>
				<key>device-id</key>
				<data>LR4AAA==</data>
				<key>device_type</key>
				<string>USB controller</string>
				<key>model</key>
				<string>7 Series/C216 Chipset Family USB Enhanced Host Controller #1</string>
			</dict>
```
</code>
Looks like fake device-id didn't work, anything I missed? Thanks.

**Comment by banhbaoxamlan** [comment]
Maybe u need disable SSDT-EHC1.aml

**Comment by Karleow** [comment]
Ya... your SSDT-EHC1.aml is actually renamed from  SSDT-EHC1_OFF.aml, one of SSDT-EHCx_OFF.aml, which disabled EHC1.
However, simply remove this will cause BigSur stuck when boot up.
Then I add SSDT-ARPT-RP0[4-7]-4352.aml from littlegtplr's project (https://github.com/littlegtplr/Hackintosh-X230-macOS/tree/master/ACPI/patched) and enable them, everything works good now. Thanks.
BTW, usbinjectall and usbmap is not needed in Big Sur, OS got all USB ports and work.
