### ISSUE TITLE
X330 Support

### ISSUE THREAD

**Issue by banhbaoxamlan** [banhbaoxamlan/X230-Hackintosh#5]
https://xyte.ch/thinkpads/x230/

**Comment by jamesfawcett** [comment]
Good link! Some helpful info on screen options there!

**Comment by banhbaoxamlan** [comment]
> Good link! Some helpful info on screen options there!

I'm waiting my X330 ^^
Will upload more config for others mod with X230 (eGPU,  Keyboard, etc ... ) :relaxed:
