### ISSUE TITLE
WiFi Intel 6205 works

### ISSUE THREAD

**Issue by Karleow** [banhbaoxamlan/X230-Hackintosh#50]
Intel 6205(and more) works by enabling itlwm.kext ( https://github.com/OpenIntelWireless/itlwm ) .
Downside is you have to fill SSDI/pwd in Info.plist, and looks like an ethernet link. But it works.

**Comment by jeremydeanw** [comment]
Hey there, how did you edit the config.plist to accommodate this? (first time for me) Cheers

**Comment by jeremydeanw** [comment]
Nevermind, issue #41 has the config file.

**Comment by banhbaoxamlan** [comment]
With Airportltlwm work OOB. Thanks.
