### ISSUE TITLE
0.5-RC3 does not boot

### ISSUE THREAD

**Issue by mcanevet** [banhbaoxamlan/X230-Hackintosh#54]
While 0.4 works like a charm, I could not get 0.5-RC3 boot.
I have some disk activity, but no Apple logo.

**Comment by banhbaoxamlan** [comment]
Edit Config.split >> DeviceProperties >> Add:
```
<string>AAPL,ig-platform-id</string>
<data>AwBmAQ=</data>
```

**Comment by mcanevet** [comment]
I tried with `master` that contains this change, but it does not work either.

**Comment by banhbaoxamlan** [comment]
> I tried with `master` that contains this change, but it does not work either.

Sorry, I edit wrong typo, please try update my latest commit.
