### ISSUE TITLE
Blank screen after boot on Big Sur (0.5 RC)

### ISSUE THREAD

**Issue by cryptosnape** [banhbaoxamlan/X230-Hackintosh#55]
Has anyone managed to properly boot Big Sur 11.3.1 with the new 0.5 RC? After updating the EFI I always get a blank screen after booting (pretty much at the point when the lockscreen should come). That "white colour" seems to start in one corner of the display and spreads all across. There's no mouse or anything else visible. With RC 0.4 everything worked just perfectly fine.

**Comment by banhbaoxamlan** [comment]
Same with #54 , you need edit AAPL,ig-platform-id

**Comment by ichsphon** [comment]
@cryptosnape if you remove everything but the ` AAPL,ig-platform-id `in `PciRoot(0x0)/Pci(0x2,0x0)` works (it worked for me)
Beside that the trackpoint in the 0.5 RC does not work in my machine

**Comment by ichsphon** [comment]
```
        <key>DeviceProperties</key>
        <dict>
                <key>Add</key>
                <dict>
                        <key>PciRoot(0x0)/Pci(0x2,0x0)</key>
                        <dict>
                                <key>AAPL,ig-platform-id</key>
                                <data>AwBmAQ==</data>
                        </dict>
                </dict>
                <key>Delete</key>
                <dict/>
        </dict>
```
