### ISSUE TITLE
is it supported with windows10 dual boot?

### ISSUE THREAD

**Issue by yanlusu** [banhbaoxamlan/X230-Hackintosh#56]
hi,
  is it supported with windows10 dual boot?

**Comment by banhbaoxamlan** [comment]
Yes but I not recommended use OC to boot, you can boot windows with F12.

**Comment by 13631181823** [comment]
we have a mod version in china. it can skip win from oc boot.
source code：
https://gitee.com/btwise/OpenCore_NO_ACPI
BBS：
http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1838814&mobile=yes

**Comment by banhbaoxamlan** [comment]
Lenovo Vantage will not work if you boot from OC 😟

**Comment by yanlusu** [comment]
> Yes but I not recommended use OC to boot, you can boot windows with F12.

OK, thx.
