### ISSUE TITLE
Stuck on boot - BuildActDeviceEntry

### ISSUE THREAD

**Issue by mcanevet** [banhbaoxamlan/X230-Hackintosh#58]
Since https://github.com/banhbaoxamlan/X230-Hackintosh/commit/5a07dacc3b5b605959863961559a12dd10068428 I'm stuck on boot on `BuildActDeviceEntry` (works with https://github.com/banhbaoxamlan/X230-Hackintosh/commit/9b80582f4e471b2f4e3021cc1255444e2e39965b)
![IMG_0006](https://user-images.githubusercontent.com/2950673/122651314-47541a80-d138-11eb-93c2-a827a5e40f12.jpg)

**Comment by cryptosnape** [comment]
I'm also having the same problem. Still couldn't find a solution to this...

**Comment by 13631181823** [comment]
find the solution！！！
please use(flash) this patched bios [https://github.com/n4ru/1vyrain/](url)
by the way, remeber turn of the SSDT-PM.aml (x230i).
The strange problem can solve, after all, the blogger is based on this BIOS environment.

> Since [5a07dac](https://github.com/banhbaoxamlan/X230-Hackintosh/commit/5a07dacc3b5b605959863961559a12dd10068428) I'm stuck on boot on `BuildActDeviceEntry` (works with [9b80582](https://github.com/banhbaoxamlan/X230-Hackintosh/commit/9b80582f4e471b2f4e3021cc1255444e2e39965b))
> ![IMG_0006](https://user-images.githubusercontent.com/2950673/122651314-47541a80-d138-11eb-93c2-a827a5e40f12.jpg)



> I'm also having the same problem. Still couldn't find a solution to this...

**Comment by mrfiskare** [comment]
I already have the modded bios, but the problem still exists. Did you do anything else?

**Comment by ghost** [comment]
I also have this problem. I have used the BIOS patch

**Comment by tupinikeebs** [comment]
Same problem with modded BIOS.

**Comment by Jan-E** [comment]
Try the fix for the boot problem that I had, described here: https://github.com/banhbaoxamlan/X230-Hackintosh/issues/67#issuecomment-894389362

Put that ‘T530’ EFI on a USB drive and boot just one time with it. Then try your normal way of booting once again.

**Comment by ghost** [comment]
> 尝试修复我的引导问题，这里描述：
> 
> 把‘T 530’EFI放在USB驱动器上，用它启动一次。然后再试一次正常的引导方式。



> Try the fix for the boot problem that I had, described here:[#67 (comment)](https://github.com/banhbaoxamlan/X230-Hackintosh/issues/67#issuecomment-894389362)
> 
> Put that ‘T530’ EFI on a USB drive and boot just one time with it. Then try your normal way of booting once again.


thank you! With this method, the problem has been solved!

**Comment by mcanevet** [comment]
Actually I have the same error message as #57.
I'll close my Issue in favour of the other.
