### ISSUE TITLE
layout-id for audio

### ISSUE THREAD

**Issue by tpadev** [banhbaoxamlan/X230-Hackintosh#6]
Hi, I just bought x230 which is identical with yours except the ram only 8GB and without dock.

Try opencore and succeed, trying to fix all the patch and stuck with the audio fix. Don’t want to try every single layout-id, thankfully I found your repo.
At first I installed Mojave but no luck with layout-id=18. I just realize that you are using latest catalina, upgrade directly from sys pref and once again opencore do the job smoothly 😁, but sadly the audio fix still not working.

Are you only using AppleALC and Lilu as mentioned in dortania guide ?
How to check if I’m using the right layout-id, is the audio device suddenly appear in sound pref ?
Result from IORegister : 
alc-layout-id = 18 (12 00 00 00)
layout-id = 7 (07 00 00 00)

Do you mind show me the process you took to make the audio fix works

Thanks

**Comment by banhbaoxamlan** [comment]
You need SSDT-HRTF.aml disabled and fake HPET, open your Config, add to ACPI>>Patch :
```
			<dict>
				<key>Enabled</key>
				<true/>
				<key>Find</key>
				<data>oBCQXFdOVEaSXFdYUEY=</data>
				<key>Replace</key>
				<data>oA9fT1NJDURhcndpbgA=</data>
			</dict>
```

**Comment by tpadev** [comment]
ok thanks, let me try that first

**Comment by banhbaoxamlan** [comment]
For codec, you need to try all support codec for ALC269VC [AppleALC Supported Codecs](https://github.com/acidanthera/AppleALC/wiki/Supported-codecs)
