### ISSUE TITLE
Wifi card issue

### ISSUE THREAD

**Issue by i0Ek3** [banhbaoxamlan/X230-Hackintosh#6]
Hi there, thank you  for your great job. But I have one question about wifi card:
I already flash the BIOS with the method you mentioned in this project. And if I want to change original wifi card with Dell DW1550 this one, is there anything else I need to do? Or I can use this new card directly? 
Thank you.

**Comment by banhbaoxamlan** [comment]
> Hi there, thank you for your great job. But I have one question about wifi card:
> I already flash the BIOS with the method you mentioned in this project. And if I want to change original wifi card with Dell DW1550 this one, is there anything else I need to do? Or I can use this new card directly?
> Thank you.

Yup, u can use directly, replace original to dw1550, it done ^^

**Comment by i0Ek3** [comment]
Thanks again!😁
