### ISSUE TITLE
No WIFI in MacOS Catalina

### ISSUE THREAD

**Issue by karelo911** [banhbaoxamlan/X230-Hackintosh#63]
I've tried installing offline using different image files as well as using the online recovery installer, still I can't get WiFi to work. I managed to generate SMBIOS as well as login to my Apple ID using Ethernet. I even figured out how to use HoRNDIS to use USB tethering from my phone. I've read from issues posted here that Intel wifi should work by default (though not optimal). I don't know if there is something I should modify in the config.plist or if I missed extra steps in installing Catalina.

Anyway, here are my specs
Thinkpad X230
Intel Core i5 3360m
Intel Centrino Advanced-N 6205

**Comment by muhrizki1996** [comment]
add this, to your OC > Config.plist > Kernel > Force

		<key>Force</key>
		<array>
			<dict>
				<key>Arch</key>
				<string>Any</string>
				<key>BundlePath</key>
				<string>System/Library/Extensions/IO80211Family.kext</string>
				<key>Comment</key>
				<string></string>
				<key>Enabled</key>
				<true/>
				<key>ExecutablePath</key>
				<string>Contents/MacOS/IO80211Family</string>
				<key>Identifier</key>
				<string>com.apple.iokit.IO80211Family</string>
				<key>MaxKernel</key>
				<string>19.99.99</string>
				<key>MinKernel</key>
				<string>17.0.0</string>
				<key>PlistPath</key>
				<string>Contents/Info.plist</string>
			</dict>
		</array>

hope this will help you.. 😁

**Comment by karelo911** [comment]
Tried your fix, still not working :(. There's no wifi icon appearing on the top right, and there is no "Wi-Fi" in System Preferences > Network. Also, I don't know if it's expected behavior but I also don't have Wi-Fi in Windows when I boot from opencore. Everything works fine though when I boot directly from the boot menu instead.

**Comment by Valeria** [comment]
Which version of the repo are you using? Itlwm kext was only recently added.

Check if you have AirportItlwm or Itlwm enabled in you OC config.plist.

Also I believe WiFi issues when dual-booting might be related to Windows having Fast Startup enabled, disabling it might be worth trying.

**Comment by karelo911** [comment]
I used both AirportItlwm built into the latest EFI release as well as the itlwm from OpenIntelWireless latest release (though not at the same time). I did modify the config.plist for each kext. I'll try disabling Windows Fast Startup and I'll update you asap if it helps, thanks.

EDIT: I did actually disable fast startup beforehand by disabling hibernation in Windows 10. So I guess I can rule out fast startup as a possible culprit.

**Comment by truongvantuan** [comment]
I have the same wifi chipset. let try this kext, that removed unnecessary WiFi firmware files https://www.dropbox.com/s/t5n9exg42imr4zf/Catalina.zip?dl=0

**Comment by karelo911** [comment]
> I have the same wifi chipset. let try this kext, that removed unnecessary WiFi firmware files https://www.dropbox.com/s/t5n9exg42imr4zf/Catalina.zip?dl=0

This fixed it. Thank you very much!

**Comment by truongvantuan** [comment]
> > I have the same wifi chipset. let try this kext, that removed unnecessary WiFi firmware files https://www.dropbox.com/s/t5n9exg42imr4zf/Catalina.zip?dl=0
> 
> This fixed it. Thank you very much!

I'm glad to help you

**Comment by stredwizard** [comment]
thankyou fixed it for me too!
