### ISSUE TITLE
Monterey: stuck during boot and a fix

### ISSUE THREAD

**Issue by Jan-E** [banhbaoxamlan/X230-Hackintosh#67]
@banhbaoxamlan Thanks for the fantastic repo. I am running this now on my X230T with an i7 3520M CPU

I used your normal EFI, adjusted it for Monterey (beta 4) and added the AirportItlwm.kext for Monterey to get my Intel WIFI card working. I also got my bluetooth working, drawing inspiration from https://github.com/5T33Z0/Lenovo-T530-Hackinosh-OpenCore/releases 

Than I ran https://github.com/chris1111/Patch-HD4000-Monterey to get everything out of my HD4000, like brightness control.

This all is happening on a machine which also has a partition with Catalina 10.15.7 and a partition with Big Sur 11.5.1. Now here comes the twist. Big Sur is started from the EFI on my SSD and runs on OpenCore 0.6.3. Monterey is started from a USB drive and runs this repo with OpenCore 0.7.1 and the OpenCore Legacy Patcher 0.2.3. Every time after switching from Big Sur or from Windows 10 to Monterey, booting stucks on Lilu finding a dead IGPU:
![IMG_0419](https://user-images.githubusercontent.com/1757825/128542327-3702c834-1058-4d07-82be-8c58a86acdb2.jpeg)
Clearing the NVRAM or changes in my BIOS did not solve this. However, I found a workaround which I will describe in a follow-up message.

**Comment by LubosKolouch** [comment]
Is the sleep working for you? Which model (Macbook, imac,...) do you have in the Config.plist?

**Comment by Jan-E** [comment]
The fix is that I created another USB drive with a slightly adjusted EFI from https://github.com/5T33Z0/Lenovo-T530-Hackinosh-OpenCore

The adjustment is that I used the config.plist for Monterey and made the screen working on 1366x968, by removing the key device_type with a value 'VGA compatible controller. See this issue: https://github.com/5T33Z0/Lenovo-T530-Hackinosh-OpenCore/issues/11 

This zip contains the EFI with the adjustments for a 1366x768 LCD: 
[Lenovo T530 OC 0.7.2 v2.0.zip](https://github.com/banhbaoxamlan/X230-Hackintosh/files/6949832/Lenovo.T530.OC.0.7.2.v2.0.zip)

The only thing I have to do to fix the 'dead IGPU' issue is to boot from a USB drive with that EFI, wait for the OpenCore menu and immediately shut down. Reboot with the EFI from this repo and the booting goes fine. With this EFI I can freely switch between Windows 10, Catalina, Big Sur and Monterey. So my next step will be to replace the OpenCore 0.6.3 on my SSD with this one with OpenCore 0.7.1.

I really do not know why the workaround works, but apparently it clears something in my system to fix the 'dead IGPU' issue.

**Comment by Jan-E** [comment]
> Is the sleep working for you? Which model (Macbook, imac,...) do you have in the Config.plist?

~~Yes, sleeping seems OK with a MacBookPro11,5.~~ I will clear my Serial number etc from the working EFI and upload it later.

**Comment by Jan-E** [comment]
This is my working EFI: 
[EFI.zip](https://github.com/banhbaoxamlan/X230-Hackintosh/files/6946980/EFI.zip)

I removed the Serial, the Board Serial (MLB), the SmUUID and the Apple ROM from the PlatformInfo > Generic. Generate new ones, using https://github.com/corpnewt/GenSMBIOS and fill those fields again with the generated ones.

Do not forget to run https://github.com/chris1111/Patch-HD4000-Monterey to make screen brightness work. I also generated a new SSDT-PM.aml for my i7 3520M, but that may not even be necessary. Use `~/ssdtPRGen.sh -target 2` to avoid the error `board-id not supported by Ivy Bridge`.

**Comment by Jan-E** [comment]
Bummer: on checking the config.plist I see now that SSDT-PM.aml is not even enabled. ACPI > Add > Item 5 Enabled. I probably disabled it to avoid issues between my i7 and the more common i5, but you might want to enable it.

**Comment by Jan-E** [comment]
First impression: with SSDT-PM.aml enabled graphics performance is worse. Streaming TV buffered a lot. I disabled it and the streaming goes smooth now.

**Comment by Jan-E** [comment]
Sleep did not work in the EFI from this repo. But it did work in the EFI from https://github.com/5T33Z0/Lenovo-T530-Hackinosh-OpenCore

**Comment by OrtizMc** [comment]
![Uploading 8D1C557C-368C-47ED-8809-191166DBEB8B.jpeg…]()

**Comment by the-r3dacted** [comment]
> This is my working EFI: [EFI.zip](https://github.com/banhbaoxamlan/X230-Hackintosh/files/6946980/EFI.zip)

Could you please help me? Your EFI works for me using Mojave, but opening the app store freezes the entire machine and requires the power button to be held until it turns off. I can't seem to find any working fix, and hackintosh places won't help me because I use a pre-built EFI, I specifically want Mojave for iTunes and x86 apps, so I don't want to go for a newer version.

The latest T530 EFI has some issues on my X230, and the author won't help me because I have a X230 even though it's literally just a smaller T530.

Please help
