### ISSUE TITLE
4MB of graphics

### ISSUE THREAD

**Issue by MaciejOzga** [banhbaoxamlan/X230-Hackintosh#73]
I successfully installed macOS Monterey, but gpu is only 4mb. I don't know what to do about it, please help.
[](https://imgur.com/cPWpCUc)

**Comment by MaciejOzga** [comment]
https://imgur.com/cPWpCUc

**Comment by Jan-E** [comment]
Did you run https://github.com/chris1111/Patch-HD4000-Monterey ?

**Comment by MaciejOzga** [comment]
Now I did and it works. Thank you!

**Comment by Jan-E** [comment]
Ok! Then please close the issue.
