### ISSUE TITLE
Can't boot on x230,i7

### ISSUE THREAD

**Issue by nhd0** [banhbaoxamlan/X230-Hackintosh#76]
cant boot with this EFI... is just say not support macos version and then shut down in 30seconds. (try catalina15.7, and big sur from 11.0-11.6 not working at all)

**Comment by memegauste** [comment]
Paste log, then.

**Comment by nhd0** [comment]
Solved!, remove moded bios to official (because moded bios wont work at all for my case), and then continue to [this](https://github.com/banhbaoxamlan/X230-Hackintosh/issues/67#issuecomment-894389362) step

Big Sur 11.6
