### ISSUE TITLE
Bluetooth no work in Big Sur 11.6.3

### ISSUE THREAD

**Issue by khseal** [banhbaoxamlan/X230-Hackintosh#77]
Hello!
Try intel ax200 bluetooth no work. No load kext.
Try ThinkPad BT module. No work.
Wi-fi works fine.
I try USBInjectAll.kext. Camera without USBInjectAll.kext no found....
![image](https://user-images.githubusercontent.com/11374629/153961288-ea8264f8-399f-4977-afbe-e0b1126deee5.png)

**Comment by khseal** [comment]
Problem solved. Update kext and add  USBInjectAll.kext. 
Camera need  USBInjectAll.kext
ThinkPad BT no works.

**Comment by prabhakaran1021** [comment]
Thanks for your time and effort  will update the same fix in troubleshooting soon.
